# Generated by Django 6.0 on 2026-07-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отдел'),
        ),
    ]
