# Generated by Django 6.0 on 2026-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descr',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
