# Generated by Django 6.0 on 2026-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='action_type',
            field=models.CharField(choices=[('created', 'Создание'), ('updated', 'Обновление'), ('status_changed', 'Изменение статуса'), ('priority_changed', 'Изменение приоритета'), ('assignee_changed', 'Изменение исполнителя'), ('comment_added', 'Добавление комментария'), ('stage_completed', 'Выполнение этапа'), ('sample_added', 'Добавление образца'), ('sample_removed', 'Удаление образца'), ('protocol_changed', 'Изменение протокола'), ('department_changed', 'Изменение отдела')], max_length=50, verbose_name='Тип действия'),
        ),
    ]
