# Generated by Django 6.0 on 2026-07-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descr',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='description'),
        ),
    ]
