# Generated by Django 6.0 on 2026-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='content',
            new_name='descr',
        ),
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
