# Generated by Django 6.0 on 2026-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_content_sample_descr_sample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='some_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
