# Generated by Django 6.0 on 2026-07-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_options_remove_task_stages_taskstage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstage',
            options={},
        ),
    ]
