# Generated by Django 6.0 on 2026-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sample_some_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='zlims_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
