# Generated by Django 6.0 on 2026-07-16 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_taskstage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='zlims_id',
        ),
        migrations.AddField(
            model_name='sample',
            name='material_type',
            field=models.CharField(blank=True, help_text='Например: кровь, ткань, ДНК, РНК, белок, клетки, бактерии, вирусы и т.д.', max_length=100, null=True, verbose_name='Тип биоматериала'),
        ),
        migrations.AddField(
            model_name='sample',
            name='project_code',
            field=models.CharField(blank=True, help_text='Сокращённое название проекта (R, B, Tom, BS и т.д.). Для PopGene оставляем пустым.', max_length=50, null=True, verbose_name='Буквенный код проекта'),
        ),
        migrations.AddField(
            model_name='sample',
            name='qc_1',
            field=models.FloatField(blank=True, null=True, verbose_name='QC параметр 1'),
        ),
        migrations.AddField(
            model_name='sample',
            name='qc_2',
            field=models.FloatField(blank=True, null=True, verbose_name='QC параметр 2'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_code',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор образца (например, 172R, 2256B, 5335BS_1, 5105)', max_length=255, null=True, verbose_name='Sample_ID'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_group_code',
            field=models.CharField(blank=True, help_text='Групповой идентификатор (Sample_ID без индекса). Используется для объединения связанных образцов.', max_length=255, null=True, verbose_name='Sample_Group_ID'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_index',
            field=models.CharField(blank=True, help_text='Числовой индекс (_1, _2, ...) для повторных выделений или поступлений.', max_length=50, null=True, verbose_name='Индекс копии'),
        ),
        migrations.AddField(
            model_name='sample',
            name='uin1',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор человека — источника биоматериала (конфиденциально).', max_length=255, null=True, verbose_name='УИН1'),
        ),
        migrations.AddField(
            model_name='sample',
            name='uin2',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор биоматериала при поступлении (штрихкод, QR-код).', max_length=255, null=True, verbose_name='УИН2'),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='sample',
            name='zlims_code',
            field=models.CharField(blank=True, help_text='12-значный числовой код (например, 000027053350)', max_length=255, null=True, verbose_name='ZLIMS_ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='descr',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внутреннее название'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='some_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дополнительный числовой идентификатор'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный пользователь'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название батча')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Отдел')),
                ('descr', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Subsample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(blank=True, help_text='Уникальный идентификатор образца (например, 172R, 2256B, 5335BS_1, 5105)', max_length=255, null=True, verbose_name='Sample_ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Внутреннее название')),
                ('some_number', models.IntegerField(blank=True, null=True, verbose_name='Дополнительный числовой идентификатор')),
                ('qc_1', models.FloatField(blank=True, null=True, verbose_name='QC параметр 1')),
                ('qc_2', models.FloatField(blank=True, null=True, verbose_name='QC параметр 2')),
                ('descr', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsamples', to='app.sample', verbose_name='Родительский образец')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='BatchSubsample',
            fields=[
                ('subsample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.subsample')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_subsamples', to='app.batch', verbose_name='Батч')),
            ],
            bases=('app.subsample',),
        ),
    ]
