# Generated by Django 6.0 on 2026-07-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_sample_zlims_id_sample_material_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
