# Generated by Django 6.0 on 2026-07-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_index',
            field=models.CharField(blank=True, help_text='Числовой индекс (_1, _2, ...) для повторных выделений или поступлений.', max_length=50, null=True, verbose_name='sample index'),
        ),
    ]
