# Generated by Django 6.0 on 2026-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_sample_sample_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='app.batch', verbose_name='Батчи'),
        ),
    ]
