# Generated by Django 6.0 on 2026-07-17 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_task_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsubsample',
            name='subsample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsamples', to='app.subsample'),
        ),
    ]
