# Generated by Django 6.0 on 2026-07-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_batchsubsample_subsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='subsamples',
            field=models.ManyToManyField(blank=True, related_name='batches', to='app.subsample', verbose_name='Подобразцы'),
        ),
        migrations.DeleteModel(
            name='BatchSubsample',
        ),
    ]
