# Generated by Django 6.0 on 2026-07-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_batch_subsamples_delete_batchsubsample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='samples',
        ),
    ]
