# Generated by Django 6.0 on 2026-08-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_task_samples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='subsamples',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='some_number',
        ),
        migrations.AddField(
            model_name='batch',
            name='samples',
            field=models.ManyToManyField(blank=True, related_name='batches', to='app.sample', verbose_name='Образцы'),
        ),
        migrations.DeleteModel(
            name='Subsample',
        ),
    ]
