# Generated by Django 6.0 on 2026-08-21

from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion


def copy_task_ids_to_generic_entity(apps, schema_editor):
    QueryHistory = apps.get_model("app", "QueryHistory")
    QueryHistory.objects.filter(entity_id__isnull=True).exclude(
        task_id__isnull=True
    ).update(entity_id=F("task_id"))


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_remove_batch_subsamples_remove_sample_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="entity_type",
            field=models.CharField(
                db_index=True,
                default="task",
                max_length=50,
                verbose_name="Тип сущности",
            ),
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="entity_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="ID сущности",
            ),
        ),
        migrations.AlterField(
            model_name="queryhistory",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="app.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterField(
            model_name="queryhistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("created", "Создание"),
                    ("deleted", "Удаление"),
                    ("updated", "Обновление"),
                    ("status_changed", "Изменение статуса"),
                    ("priority_changed", "Изменение приоритета"),
                    ("assignee_changed", "Изменение исполнителя"),
                    ("comment_added", "Добавление комментария"),
                    ("stage_completed", "Выполнение этапа"),
                    ("sample_added", "Добавление образца"),
                    ("sample_removed", "Удаление образца"),
                    ("protocol_changed", "Изменение протокола"),
                    ("department_changed", "Изменение отдела"),
                ],
                max_length=50,
                verbose_name="Тип действия",
            ),
        ),
        migrations.AddIndex(
            model_name="queryhistory",
            index=models.Index(
                fields=["entity_type", "entity_id", "-created_at"],
                name="queryhistory_entity_idx",
            ),
        ),
        migrations.RunPython(copy_task_ids_to_generic_entity, migrations.RunPython.noop),
    ]
